"""rename book.

Revision ID: 35136857d9f4
Revises: c9a374ee61b6
Create Date: 2024-07-22 22:03:59.624714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35136857d9f4'
down_revision = 'c9a374ee61b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_link', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('filename', sa.String(length=30), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('filename')
        batch_op.drop_column('image_link')

    # ### end Alembic commands ###
