"""fixed rent

Revision ID: 759027446781
Revises: d497f38865c5
Create Date: 2024-07-25 02:30:48.212113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759027446781'
down_revision = 'd497f38865c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('end_rent',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('end_rent',
               existing_type=sa.String(length=15),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
